services:

  db:
    image: postgres:17

    container_name: postgres-db

    restart: always

    env_file:
      - .env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: notes-api

    restart: always

    depends_on:
      - db

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000

    container_name: notes-frontend

    restart: always

    depends_on:
      - api

    ports:
      - "5173:80"

volumes:
  postgres_data:
